### ISSUE TITLE
Send image to VM and replicate "n" times.

### ISSUE THREAD

**Issue by fgan1** [thiagomanel/SEBAL-automation#9]
- Send image to VM
- Replicate "n" times
- Put in Crawler

Tip: https://github.com/thiagomanel/SEBAL-automation/blob/master/bin/run#L41
https://github.com/thiagomanel/SEBAL-automation/blob/master/bin/run#L53

**Comment by EsdrasVP** [comment]
7fa6ce6a139de277d2f6cd4f21dc7be9f26fb729
